2025-03-08 16:07:18,523 - 26 - root - INFO - Entered the data ingestion method or compponent
2025-03-08 16:07:18,556 - 32 - root - INFO - reading the dataset as dataframe
2025-03-08 16:07:18,556 - 57 - root - ERROR - Error reading dataset
Traceback (most recent call last):
  File "c:\Users\Rotim\OneDrive\Documents\Data_Science_Projects\Student_ML_Project\src\components\data_ingestion.py", line 37, in initiate_data_ingestion
    os.makedirs(artifacts_dir, exist_ok=True)
NameError: name 'artifacts_dir' is not defined
