2025-03-08 16:19:30,354 - 26 - root - INFO - Entered the data ingestion method or compponent
2025-03-08 16:19:30,370 - 32 - root - INFO - reading the dataset as dataframe
2025-03-08 16:19:30,370 - 57 - root - ERROR - Error reading dataset
Traceback (most recent call last):
  File "c:\Users\Rotim\OneDrive\Documents\Data_Science_Projects\Student_ML_Project\src\components\data_ingestion.py", line 43, in initiate_data_ingestion
    df.to_csv(self.ingestion_config.raw_data_data_path, index = False, header= True)
  File "C:\Users\Rotim\OneDrive\Documents\Data_Science_Projects\Student_ML_Project\venv\lib\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Rotim\OneDrive\Documents\Data_Science_Projects\Student_ML_Project\venv\lib\site-packages\pandas\core\generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "C:\Users\Rotim\OneDrive\Documents\Data_Science_Projects\Student_ML_Project\venv\lib\site-packages\pandas\io\formats\format.py", line 1014, in to_csv
    csv_formatter.save()
  File "C:\Users\Rotim\OneDrive\Documents\Data_Science_Projects\Student_ML_Project\venv\lib\site-packages\pandas\io\formats\csvs.py", line 251, in save
    with get_handle(
  File "C:\Users\Rotim\OneDrive\Documents\Data_Science_Projects\Student_ML_Project\venv\lib\site-packages\pandas\io\common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "C:\Users\Rotim\OneDrive\Documents\Data_Science_Projects\Student_ML_Project\venv\lib\site-packages\pandas\io\common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'artifacts'
